### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pingguo114514** [GroupMountain/Cleaner#5]
LeviLamina版本：0.8.1

BDS版本：1.20.62

1. 重载插件报错

00:42:05.961 ERROR [LeviLamina] Error in command cleaner:

00:42:05.963 ERROR [LeviLamina] Raw Seh Exception:

00:42:05.966 ERROR [LeviLamina] [0xC0000005:ntstatus] 0x%p 指令引用了 0x%p 内存。该内存不能为 %s。

00:42:05.968 ERROR [LeviLamina] Parameter 0: 0x1

00:42:05.970 ERROR [LeviLamina] Parameter 1: 0x51

2.即使没有开启在tps过低时清理，仍然启用这个功能

3.即使没有开启自定义掉落物存在时间，仍然会启用这个功能

4.将矿车识别成生物，而不是非生物实体

**Comment by Tsubasa6848** [comment]
重载是如何重载的，我无法复现

**Comment by Tsubasa6848** [comment]
已修复
