### ISSUE TITLE
cleaner会让服务器假死，触发条件 可能是 管理员不在服务器里。我服主本人在服务器就没遇到过假死都是我不在的时候假死，我这么推断的

### ISSUE THREAD

**Issue by enzo123456fes** [GroupMountain/Cleaner#8]
cleaner会让服务器假死，触发条件 可能是 管理员不在服务器里。我服主本人在服务器就没遇到过假死都是我不在的时候假死，我这么推断的

**Comment by Tsubasa6848** [comment]
经查明，这个问题和LL本身有关系，LSE死锁也是同样的原因。

**Comment by yufengya0420** [comment]
> 经查明，这个问题和LL本身有关系，LSE死锁也是同样的原因。

ll0.9.3修了，应该不会假死了
