### ISSUE TITLE
快点适配gmlib0.9.4和ll0.9.3

### ISSUE THREAD

**Issue by ye111566** [GroupMountain/Cleaner#9]
10:43:53.703 ERROR [LeviLamina] C++ Exception: std::system_error, from <LeviLamina>:
10:43:53.703 ERROR [LeviLamina] [0x0000007F:system] 找不到指定的程序。
10:43:53.703 ERROR [LeviLamina] current stacktrace:
10:43:53.703 ERROR [LeviLamina] 0> at: 0x7FFCCE5C3C88 LeviLamina -> ll::plugin::NativePluginManager::load + 0x2B8 [NativePluginManager.cpp:78L]
10:43:53.703 ERROR [LeviLamina] 1> at: 0x7FFCCE4E9F01 LeviLamina -> ll::plugin::PluginManagerRegistry::loadPlugin + 0x191 [PluginManagerRegistry.cpp:27L]
10:43:53.703 ERROR [LeviLamina] 2> at: 0x7FFCCE5CDD36 LeviLamina -> ll::plugin::PluginRegistrar::loadAllPlugins + 0x1666 [PluginRegistrar.cpp:237L]
10:43:53.703 ERROR [LeviLamina] 3> at: 0x7FFCCE5BE2D7 LeviLamina -> ll::leviLaminaMain + 0x2B7 [LeviLamina.cpp:260L]
10:43:53.703 ERROR [LeviLamina] 4> at: 0x7FFCCE5BE5B5 LeviLamina -> ll::LeviLaminaMainHook::detour + 0x2B5 [LeviLamina.cpp:288L]
10:43:53.719 ERROR [LeviLamina] 5> at: 0x7FF705AE12C8 bedrock_server_mod -> __scrt_common_main_seh + 0x10C
10:43:53.719 ERROR [LeviLamina] 6> at: 0x7FFCF3774ED0 KERNEL32 + 0x14ED0
10:43:53.719 ERROR [LeviLamina] 7> at: 0x7FFCF4B7E39B ntdll + 0x7E39B
10:43:55.891 ERROR [LeviLamina] Dependency diagnostic:
   module: D:\新建文件夹\plugins\Cleaner\Cleaner.dll
   missing procedure:
   |- LeviLamina.dll
   |---- ?listMutex@detail@thread@ll@@3Vmutex@std@@A
   |     class std::mutex ll::thread::detail::listMutex
   |---- ?poolListSize@detail@thread@ll@@3U?$atomic@_K@std@@A
   |     struct std::atomic<unsigned __int64> ll::thread::detail::poolListSize
   |---- ?tickListSize@detail@thread@ll@@3U?$atomic@_K@std@@A
   |     struct std::atomic<unsigned __int64> ll::thread::detail::tickListSize
   |---- ?notify@detail@thread@ll@@YAXXZ
   |     void __cdecl ll::thread::detail::notify(void)
   |---- ?poolList@detail@thread@ll@@3V?$vector@V?$reference_wrapper@VTickSyncTaskPool@thread@ll@@@std@@V?$allocator@V?$reference_wrapper@VTickSyncTaskPool@thread@ll@@@std@@@2@@std@@A
   |     class std::vector<class std::reference_wrapper<class ll::thread::TickSyncTaskPool>, class std::allocator<class std::reference_wrapper<class ll::thread::TickSyncTaskPool>>> ll::thread::detail::poolList
   |---- ?poolListMutex@detail@thread@ll@@3Vmutex@std@@A
   |     class std::mutex ll::thread::detail::poolListMutex
   |---- ?tickList@detail@thread@ll@@3V?$vector@V?$variant@V?$reference_wrapper@V?$TickSyncSleep@UServerClock@chrono@ll@@@thread@ll@@@std@@V?$reference_wrapper@V?$TickSyncSleep@UGameTickClock@chrono@ll@@@thread@ll@@@2@@std@@V?$allocator@V?$variant@V?$reference_wrapper@V?$TickSyncSleep@UServerClock@chrono@ll@@@thread@ll@@@std@@V?$reference_wrapper@V?$TickSyncSleep@UGameTickClock@chrono@ll@@@thread@ll@@@2@@std@@@2@@std@@A
   |     class std::vector<class std::variant<class std::reference_wrapper<class ll::thread::TickSyncSleep<struct ll::chrono::ServerClock>>, class std::reference_wrapper<class ll::thread::TickSyncSleep<struct ll::chrono::GameTickClock>>>, class std::allocator<class std::variant<class std::reference_wrapper<class ll::thread::TickSyncSleep<struct ll::chrono::ServerClock>>, class std::reference_wrapper<class ll::thread::TickSyncSleep<struct ll::chrono::GameTickClock>>>>> ll::thread::detail::tickList
   |---- ?notifyWorker@detail@thread@ll@@YAXXZ
   |     void __cdecl ll::thread::detail::notifyWorker(void)

10:43:55.891 ERROR [LeviLamina] Cleaner 加载失败

**Comment by yufengya0420** [comment]
已经适配了

**Comment by Tsubasa6848** [comment]
> 10:43:53.703 ERROR [LeviLamina] C++ Exception: std::system_error, from : 10:43:53.703 ERROR [LeviLamina] [0x0000007F:system] 找不到指定的程序。 10:43:53.703 ERROR [LeviLamina] current stacktrace: 10:43:53.703 ERROR [LeviLamina] 0> at: 0x7FFCCE5C3C88 LeviLamina -> ll::plugin::NativePluginManager::load + 0x2B8 [NativePluginManager.cpp:78L] 10:43:53.703 ERROR [LeviLamina] 1> at: 0x7FFCCE4E9F01 LeviLamina -> ll::plugin::PluginManagerRegistry::loadPlugin + 0x191 [PluginManagerRegistry.cpp:27L] 10:43:53.703 ERROR [LeviLamina] 2> at: 0x7FFCCE5CDD36 LeviLamina -> ll::plugin::PluginRegistrar::loadAllPlugins + 0x1666 [PluginRegistrar.cpp:237L] 10:43:53.703 ERROR [LeviLamina] 3> at: 0x7FFCCE5BE2D7 LeviLamina -> ll::leviLaminaMain + 0x2B7 [LeviLamina.cpp:260L] 10:43:53.703 ERROR [LeviLamina] 4> at: 0x7FFCCE5BE5B5 LeviLamina -> ll::LeviLaminaMainHook::detour + 0x2B5 [LeviLamina.cpp:288L] 10:43:53.719 ERROR [LeviLamina] 5> at: 0x7FF705AE12C8 bedrock_server_mod -> __scrt_common_main_seh + 0x10C 10:43:53.719 ERROR [LeviLamina] 6> at: 0x7FFCF3774ED0 KERNEL32 + 0x14ED0 10:43:53.719 ERROR [LeviLamina] 7> at: 0x7FFCF4B7E39B ntdll + 0x7E39B 10:43:55.891 ERROR [LeviLamina] Dependency diagnostic: module: D:\新建文件夹\plugins\Cleaner\Cleaner.dll missing procedure: |- LeviLamina.dll |---- ?listMutex@detail@thread@ll@@3Vmutex@std@@A | class std::mutex ll::thread::detail::listMutex |---- ?poolListSize@detail@thread@ll@@3u?$atomic@_K@std@@A | struct std::atomic ll::thread::detail::poolListSize |---- ?tickListSize@detail@thread@ll@@3u?$atomic@_K@std@@A | struct std::atomic ll::thread::detail::tickListSize |---- ?notify@detail@thread@ll@@yaxxz | void __cdecl ll::thread::detail::notify(void) |---- ?poolList@detail@thread@ll@@3v?$vector@V?$reference_wrapper@VTickSyncTaskPool@thread@ll@@@std@@v?$allocator@V?$reference_wrapper@VTickSyncTaskPool@thread@ll@@@std@@@2@@std@@A | class std::vector<class std::reference_wrapper, class std::allocator<class std::reference_wrapper>> ll::thread::detail::poolList |---- ?poolListMutex@detail@thread@ll@@3Vmutex@std@@A | class std::mutex ll::thread::detail::poolListMutex |---- ?tickList@detail@thread@ll@@3v?$vector@V?$variant@V?$reference_wrapper@V?$TickSyncSleep@UServerClock@chrono@ll@@@thread@ll@@@std@@v?$reference_wrapper@V?$TickSyncSleep@UGameTickClock@chrono@ll@@@thread@ll@@@2@@std@@v?$allocator@V?$variant@V?$reference_wrapper@V?$TickSyncSleep@UServerClock@chrono@ll@@@thread@ll@@@std@@v?$reference_wrapper@V?$TickSyncSleep@UGameTickClock@chrono@ll@@@thread@ll@@@2@@std@@@2@@std@@A | class std::vector<class std::variant<class std::reference_wrapper<class ll::thread::TickSyncSleep>, class std::reference_wrapper<class ll::thread::TickSyncSleep>>, class std::allocator<class std::variant<class std::reference_wrapper<class ll::thread::TickSyncSleep>, class std::reference_wrapper<class ll::thread::TickSyncSleep>>>> ll::thread::detail::tickList |---- ?notifyWorker@detail@thread@ll@@yaxxz | void __cdecl ll::thread::detail::notifyWorker(void)
> 
> 10:43:55.891 ERROR [LeviLamina] Cleaner 加载失败

v0.9.0适配了啊
